<?php
/**
 * Created by PhpStorm.
 * User: Yinmin
 * Date: 2017/7/7
 * Time: 下午 02:46
 */

namespace Main\View\pika;


use Windwalker\Core\View\HtmlView;

class PikaHtmlView extends HtmlView
{
    protected function prepareData($data)
    {
        // 調整錢的格式
        if ($this->getLayout() === 'default')
        {
            // $data->name = 'yinmin'; // TODO: Change the autogenerated stub
            //Format save
            $data->save = 'NT$ ' . number_format(round($data->save), 0);
        }
        else if ($this->getLayout() === 'members')
        {
            foreach ($data->members as $member)
            {
                $member->save ='NT$ ' . number_format(round($member->save), 0);
            }
        }


    }
}